import { useState, useEffect } from "react";

// ── DATA ──────────────────────────────────────────────────────────────
const DEFAULT_PROJECTS = [
  {
    id: "anniversary",
    title: "ANNIVERSARY CELEBRATION VIDEO",
    tag: "VIDEO",
    desc: "Cinematic anniversary celebration video capturing romantic moments and special guest messages.",
    progress: 0,
    deadline: "Jun 15, 2026",
    avatars: [5],
    status: "PENDING",
    st: "rq",
    cat: "ONGOING",
    step: 1,
    collab: "Kim Veny",
    collabImg: 5,
    isMain: true,
  },
  {
    id: "coffee",
    title: "MOBILE APP COFFEE",
    tag: "MOBILE",
    desc: "Developing a coffee ordering and delivery service system application.",
    progress: 25,
    deadline: "Dec 30, 2025",
    avatars: [1, 2, 3],
    status: "IN PROGRESS",
    st: "ip",
    cat: "ONGOING",
    step: 2,
    collab: "Elena Visions",
    collabImg: 1,
    isMain: false,
  },
  {
    id: "p1",
    title: "CLOUDSCALE AI INTERFACE",
    tag: "UI/UX",
    desc: "Developing a data-heavy dashboard for enterprise AI monitoring.",
    progress: 65,
    deadline: "Dec 12, 2025",
    avatars: [11, 12],
    status: "IN PROGRESS",
    st: "ip",
    cat: "ONGOING",
    step: 2,
    collab: "CloudScale Team",
    collabImg: 11,
  },
  {
    id: "p2",
    title: "Z-CRYPT WALLET DESIGN",
    tag: "MOBILE",
    desc: "Designing a secure and minimal crypto wallet for mobile platforms.",
    progress: 30,
    deadline: "Jan 05, 2026",
    avatars: [21],
    status: "IN REVIEW",
    st: "rv",
    cat: "ONGOING",
    step: 3,
    collab: "Z-Crypt Labs",
    collabImg: 21,
  },
  {
    id: "p3",
    title: "E-MOTION AD CAMPAIGN",
    tag: "3D Animation",
    desc: "Global motion graphics campaign for an electric vehicle startup.",
    progress: 100,
    deadline: "Dec 01, 2025",
    avatars: [31, 32],
    status: "COMPLETED",
    st: "cp",
    cat: "COMPLETED",
    step: 4,
    collab: "E-Motion Studio",
    collabImg: 31,
  },
];

const TRACK_W = { 1: "0%", 2: "25%", 3: "50%", 4: "75%" };

const FILES = [
  {
    key: "uiux",
    name: "UI/UX Project",
    type: "ZIP File",
    filename: "UIUXProject_FreeLanZ.zip",
    content: "Dummy UI/UX Project files\n\nFigma exports, wireframes, prototypes, style guide.\nGenerated by FreeLanZ Platform.",
  },
  {
    key: "assets",
    name: "Assets",
    type: "ZIP File",
    filename: "Assets_FreeLanZ.zip",
    content: "Dummy Assets files\n\nIcons, illustrations, images, fonts.\nGenerated by FreeLanZ Platform.",
  },
];

// ── STYLES ────────────────────────────────────────────────────────────
const styles = `
  @import url('https://fonts.googleapis.com/css2?family=Inter:wght@400;600;700;800;900&display=swap');

  .flz-wrap { font-family: 'Inter', sans-serif; background: #f4f6fa; color: #333; min-height: 100vh; width: 100%; box-sizing: border-box; }
  .flz-wrap * { box-sizing: border-box; }

  /* HEADER */
  .flz-hdr { background: #000066; padding: 14px 5%; display: flex; justify-content: space-between; align-items: center; }
  .flz-logo { color: #ccff00; font-size: 22px; font-weight: 900; font-style: italic; letter-spacing: -1px; cursor: pointer; }
  .flz-nav { display: flex; gap: 24px; list-style: none; padding: 0; margin: 0; }
  .flz-nav a { color: white; text-decoration: none; font-size: 11px; font-weight: 700; letter-spacing: .5px; cursor: pointer; }
  .flz-nav a.active { color: #ccff00; }
  .flz-user { display: flex; align-items: center; gap: 8px; color: white; font-size: 11px; font-weight: 700; }
  .flz-avatar-sm { width: 30px; height: 30px; border-radius: 50%; background: #e0e0e0; display: flex; align-items: center; justify-content: center; color: #333; font-size: 13px; }

  /* CONTAINER */
  .flz-container { max-width: 1000px; margin: 0 auto; padding: 28px 20px; }

  /* HERO */
  .flz-hero { background: white; border-radius: 12px; padding: 22px 25px; box-shadow: 0 2px 10px rgba(0,0,0,.03); margin-bottom: 22px; }
  .flz-badge { display: inline-flex; align-items: center; gap: 7px; background: #0e056d; color: white; font-size: 9px; font-weight: 800; padding: 5px 13px; border-radius: 20px; margin-bottom: 13px; letter-spacing: .5px; }
  .flz-badge-dot { width: 7px; height: 7px; background: #ccff00; border-radius: 50%; display: inline-block; }
  .flz-hero-row { display: flex; justify-content: space-between; align-items: center; gap: 16px; }
  .flz-hero-title h1 { font-size: 26px; font-weight: 900; color: #111; letter-spacing: -.5px; margin: 0; }
  .flz-hero-title p { font-size: 12px; color: #7c7c9c; margin: 6px 0 0; }
  .flz-collab { border: 1px solid #eee; padding: 9px 14px; border-radius: 10px; display: flex; align-items: center; gap: 11px; background: #fafafa; flex-shrink: 0; }
  .flz-collab-info span { font-size: 10px; color: #888; display: block; }
  .flz-collab-info strong { font-size: 12px; color: #111; }
  .flz-collab img { width: 34px; height: 34px; border-radius: 50%; }

  /* STEPPER */
  .flz-stepper-card { background: white; border-radius: 12px; padding: 28px 40px; box-shadow: 0 2px 10px rgba(0,0,0,.03); margin-bottom: 22px; }
  .flz-stepper-wrap { position: relative; display: flex; justify-content: space-between; align-items: flex-start; }
  .flz-track-bg { position: absolute; top: 19px; left: 12.5%; width: 75%; height: 3px; background: #e0e0e0; border-radius: 2px; z-index: 0; }
  .flz-track-active { position: absolute; top: 19px; left: 12.5%; height: 3px; background: #0055ff; border-radius: 2px; z-index: 1; transition: width .45s ease; }
  .flz-step { position: relative; z-index: 2; text-align: center; flex: 1; }
  .flz-step-circle { width: 40px; height: 40px; border-radius: 50%; display: flex; align-items: center; justify-content: center; margin: 0 auto 9px; font-weight: 800; font-size: 14px; border: 3px solid #ddd; background: white; color: #bbb; transition: all .35s; }
  .flz-step.completed .flz-step-circle { background: #000066; border-color: #000066; color: white; }
  .flz-step.active .flz-step-circle { background: white; border-color: #0055ff; color: #0055ff; box-shadow: 0 0 0 4px rgba(0,85,255,.15); }
  .flz-step.todo .flz-step-circle { background: white; border-color: #ddd; color: #bbb; }
  .flz-step p { font-size: 10px; font-weight: 700; color: #bbb; margin: 0; }
  .flz-step.active p { color: #0055ff; }
  .flz-step.completed p { color: #000066; }

  /* FINAL CARD — step 3: waiting review */
  .flz-final-card { background: #000066; border-radius: 12px; padding: 26px; color: white; margin-bottom: 22px; animation: flzSlideIn .35s ease; }
  @keyframes flzSlideIn { from { opacity:0; transform:translateY(-8px); } to { opacity:1; transform:translateY(0); } }
  .flz-final-card h2 { font-size: 18px; font-weight: 800; margin: 0 0 18px; }

  /* File boxes — original style: white bg */
  .flz-file-row { display: flex; gap: 16px; margin-bottom: 22px; }
  .flz-file-box { flex: 1; background: white; border-radius: 8px; padding: 14px 18px; display: flex; justify-content: space-between; align-items: center; }
  .flz-file-info h4 { font-size: 13px; font-weight: 800; color: #111; margin: 0 0 3px; }
  .flz-file-info span { font-size: 10px; color: #888; }
  .flz-dl-btn { background: none; border: none; cursor: pointer; font-size: 18px; color: #555; transition: transform .15s; }
  .flz-dl-btn:hover { transform: scale(1.2); color: #000066; }

  .flz-action-row { display: flex; justify-content: center; gap: 12px; }
  .flz-btn { padding: 10px 26px; border-radius: 8px; font-size: 11px; font-weight: 800; border: none; cursor: pointer; min-width: 108px; transition: all .2s; }
  .flz-btn-revisi { background: white; color: black; }
  .flz-btn-revisi:hover { background: #f0f0f0; }
  .flz-btn-approve { background: #39ff14; color: #000; box-shadow: 0 0 10px rgba(57,255,20,.4); }
  .flz-btn-approve:hover { box-shadow: 0 0 20px rgba(57,255,20,.7); transform: scale(1.03); }

  /* APPROVED BANNER — step 4 replacement for final card */
  .flz-approved-banner {
    background: #000066; border-radius: 12px; padding: 26px 30px;
    color: white; margin-bottom: 22px;
    display: flex; align-items: center; gap: 18px;
    animation: flzSlideIn .35s ease;
  }
  .flz-approved-icon {
    width: 52px; height: 52px; border-radius: 50%;
    background: #39ff14; display: flex; align-items: center;
    justify-content: center; font-size: 22px; flex-shrink: 0;
    box-shadow: 0 0 16px rgba(57,255,20,.5);
  }
  .flz-approved-text h3 { font-size: 16px; font-weight: 800; margin: 0 0 4px; }
  .flz-approved-text p { font-size: 12px; color: rgba(255,255,255,.7); margin: 0; }

  /* RATING CARD — shown at step 4 */
  .flz-rating-card {
    background: white; border-radius: 12px; padding: 30px;
    box-shadow: 0 2px 10px rgba(0,0,0,.04); margin-bottom: 22px;
    animation: flzSlideIn .35s ease;
  }
  .flz-rating-card h2 { font-size: 18px; font-weight: 800; color: #111; margin: 0 0 6px; text-align: center; }
  .flz-rating-card .flz-rating-sub { font-size: 12px; color: #888; text-align: center; margin-bottom: 20px; }
  .flz-stars { display: flex; justify-content: center; gap: 10px; margin-bottom: 20px; }
  .flz-star { font-size: 36px; cursor: pointer; color: #ddd; transition: color .2s, transform .15s; line-height: 1; }
  .flz-star:hover { transform: scale(1.15); }
  .flz-star.active { color: #ffcc00; }
  .flz-rating-label { display: block; font-size: 12px; font-weight: 700; color: #333; margin-bottom: 8px; text-align: left; }
  .flz-rating-textarea {
    width: 100%; min-height: 110px; border: 1px solid #e2e8f0;
    border-radius: 8px; padding: 12px 14px; resize: none;
    font-family: inherit; font-size: 12px; color: #333;
    outline: none; transition: border-color .2s;
    margin-bottom: 20px;
  }
  .flz-rating-textarea:focus { border-color: #000066; }
  .flz-rating-actions { display: flex; justify-content: flex-end; gap: 12px; }
  .flz-btn-cancel { background: transparent; border: 1px solid #ccc; color: #555; padding: 10px 22px; border-radius: 8px; font-size: 11px; font-weight: 800; cursor: pointer; }
  .flz-btn-submit { background: #000066; color: white; padding: 10px 22px; border-radius: 8px; font-size: 11px; font-weight: 800; border: none; cursor: pointer; }
  .flz-btn-submit:hover { background: #0000aa; }

  /* RATING DONE STATE */
  .flz-rated-banner {
    background: white; border-radius: 12px; padding: 28px 30px;
    box-shadow: 0 2px 10px rgba(0,0,0,.04); margin-bottom: 22px;
    text-align: center; animation: flzSlideIn .35s ease;
  }
  .flz-rated-icon { font-size: 44px; margin-bottom: 10px; }
  .flz-rated-banner h3 { font-size: 16px; font-weight: 800; color: #000066; margin: 0 0 6px; }
  .flz-rated-banner p { font-size: 12px; color: #888; margin: 0; }
  .flz-rated-stars { display: flex; justify-content: center; gap: 6px; margin: 12px 0 0; font-size: 22px; }

  /* WORK PROJECT */
  .flz-section-title { color: #000066; font-size: 20px; font-weight: 900; margin-bottom: 14px; }
  .flz-tabs { display: flex; gap: 34px; border-bottom: 2px solid #e2e8f0; margin-bottom: 16px; }
  .flz-tab { padding-bottom: 10px; font-size: 10px; font-weight: 800; cursor: pointer; color: #94a3b8; position: relative; }
  .flz-tab.active { color: #000066; }
  .flz-tab.active::after { content:""; position:absolute; bottom:-2px; left:0; width:100%; height:2px; background:#000066; }
  .flz-proj-list { display: flex; flex-direction: column; gap: 10px; }
  .flz-proj-card { background: white; border-radius: 8px; padding: 15px 20px; display: flex; justify-content: space-between; align-items: center; border: 1px solid #edf2f7; cursor: pointer; transition: box-shadow .2s; }
  .flz-proj-card:hover { box-shadow: 0 3px 12px rgba(0,0,0,.06); }
  .flz-proj-card.selected { border-color: #0055ff; box-shadow: 0 0 0 2px rgba(0,85,255,.1); }
  .flz-card-left { flex: 1; }
  .flz-card-left h3 { font-size: 13px; font-weight: 800; color: #1a202c; display: flex; align-items: center; gap: 7px; margin: 0 0 5px; }
  .flz-tag { font-size: 9px; background: #edf2f7; color: #718096; padding: 2px 5px; border-radius: 4px; font-weight: 600; }
  .flz-card-left p { font-size: 10px; color: #7c7c9c; margin: 0 0 9px; }
  .flz-prog-row { display: flex; align-items: center; gap: 10px; font-size: 9px; color: #718096; font-weight: 700; }
  .flz-bar { width: 108px; height: 5px; background: #edf2f7; border-radius: 3px; overflow: hidden; }
  .flz-fill { height: 100%; border-radius: 3px; transition: width .5s; }
  .flz-fill.ip { background: #f5c800; }
  .flz-fill.rv { background: #ff6a00; }
  .flz-fill.rq { background: #0055ff; }
  .flz-fill.cp { background: #39ff14; }
  .flz-card-right { display: flex; align-items: center; gap: 20px; }
  .flz-card-date { font-size: 10px; color: #7c7c9c; text-align: right; }
  .flz-card-date small { display: block; font-size: 9px; color: #a0aec0; }
  .flz-avatars { display: flex; }
  .flz-avatars img { width: 22px; height: 22px; border-radius: 50%; border: 2px solid white; margin-left: -5px; }
  .flz-pill { padding: 5px 11px; border-radius: 6px; font-size: 8px; font-weight: 800; text-align: center; min-width: 80px; letter-spacing: .4px; white-space: nowrap; }
  .flz-pill.ip { background: #f5c800; color: #000; }
  .flz-pill.rv { background: #ff6a00; color: #fff; }
  .flz-pill.rq { background: #0055ff; color: #fff; }
  .flz-pill.cp { background: #39ff14; color: #000; }

  /* DETAIL BOX */
  .flz-detail-box { background: white; border-radius: 10px; padding: 20px; margin-top: 12px; border: 2px solid #000066; }
  .flz-detail-hdr { display: flex; justify-content: space-between; align-items: center; border-bottom: 1px solid #eee; padding-bottom: 8px; margin-bottom: 12px; }
  .flz-detail-hdr h3 { font-size: 14px; font-weight: 900; color: #000066; margin: 0; }
  .flz-close-btn { background: none; border: none; color: #ff0055; font-weight: 800; cursor: pointer; font-size: 11px; }
  .flz-detail-meta { display: flex; gap: 16px; font-size: 11px; margin-top: 10px; }

  /* MODAL */
  .flz-modal-bg { display: none; position: fixed; top:0; left:0; width:100%; height:100%; background:rgba(0,0,0,.5); z-index:9999; align-items:center; justify-content:center; }
  .flz-modal-bg.show { display: flex; }
  .flz-modal-box { background: white; border-radius: 16px; padding: 32px 22px 22px; max-width: 380px; width: 90%; text-align: center; position: relative; animation: flzPopIn .25s ease; }
  @keyframes flzPopIn { from { transform:scale(.9); opacity:0; } to { transform:scale(1); opacity:1; } }
  .flz-modal-close { position: absolute; top:10px; right:14px; background:none; border:none; font-size:20px; cursor:pointer; color:#999; }
  .flz-success-ring { width: 64px; height: 64px; border-radius: 50%; background: #39ff14; display: flex; align-items: center; justify-content: center; margin: 0 auto 16px; font-size: 26px; }
  .flz-modal-title { font-size: 20px; font-weight: 800; margin-bottom: 7px; color: #111; }
  .flz-modal-sub { font-size: 12px; color: #666; margin-bottom: 20px; line-height: 1.6; }
  .flz-modal-btn { background: #39ff14; color: black; border: none; padding: 10px 26px; border-radius: 9px; font-size: 11px; font-weight: 800; cursor: pointer; }
  .flz-modal-btn-sec { background: white; color: #333; border: 1.5px solid #ddd; padding: 10px 26px; border-radius: 9px; font-size: 11px; font-weight: 800; cursor: pointer; margin-right: 8px; }

  /* SUCCESS POPUP (full screen, after rating submit) */
  .flz-success-popup {
    position: fixed; top:0; left:0; width:100%; height:100%;
    background: rgba(255,255,255,.93); z-index: 10000;
    display: flex; flex-direction: column; align-items: center; justify-content: center;
    text-align: center; animation: flzFadeIn .3s ease;
  }
  @keyframes flzFadeIn { from { opacity:0; } to { opacity:1; } }
  .flz-popup-icon { font-size: 80px; color: #2ecc71; margin-bottom: 20px; }
  .flz-popup-h2 { color: #000066; font-size: 22px; font-weight: 800; margin-bottom: 10px; }
  .flz-popup-p { color: #666; font-size: 13px; margin-bottom: 24px; }
  .flz-popup-btn { background: #ccff00; border: none; padding: 12px 32px; border-radius: 25px; font-weight: 800; font-size: 13px; cursor: pointer; }
`;

// ── COMPONENTS ────────────────────────────────────────────────────────

function Stepper({ step }) {
  const LABELS = ["", "Request", "In Progress", "Review", "Completed"];
  return (
    <div className="flz-stepper-wrap">
      <div className="flz-track-bg" />
      <div className="flz-track-active" style={{ width: TRACK_W[step] }} />
      {[1, 2, 3, 4].map((i) => {
        let cls = "todo";
        if (i < step) cls = "completed";
        else if (i === step) cls = "active";
        return (
          <div key={i} className={`flz-step ${cls}`}>
            <div className="flz-step-circle">{i < step ? "✓" : `0${i}`}</div>
            <p>{LABELS[i]}</p>
          </div>
        );
      })}
    </div>
  );
}

// Step 3 card: file download + approve/revisi buttons
function FinalCard({ onApprove, onDecline }) {
  const handleDownload = (file) => {
    const blob = new Blob([file.content], { type: "application/zip" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = file.filename;
    a.click();
    URL.revokeObjectURL(url);
  };

  return (
    <div className="flz-final-card">
      <h2>Final Project Documentation</h2>
      <div className="flz-file-row">
        {FILES.map((f) => (
          <div className="flz-file-box" key={f.key}>
            <div className="flz-file-info">
              <h4>{f.name}</h4>
              <span>{f.type}</span>
            </div>
            <button className="flz-dl-btn" onClick={() => handleDownload(f)} title="Download">
              ⬇
            </button>
          </div>
        ))}
      </div>
      <div className="flz-action-row">
        <button className="flz-btn flz-btn-revisi" onClick={onDecline}>Revisi</button>
        <button className="flz-btn flz-btn-approve" onClick={onApprove}>✓ Approve</button>
      </div>
    </div>
  );
}

// Step 4: approved banner (replaces final card)
function ApprovedBanner({ project }) {
  return (
    <div className="flz-approved-banner">
      <div className="flz-approved-icon">✓</div>
      <div className="flz-approved-text">
        <h3>You approved this project!</h3>
        <p>Great collaboration with {project?.collab ?? "the team"}. Project is now completed.</p>
      </div>
    </div>
  );
}

// Step 4: rating card (from ProjectEvaluation)
function RatingCard({ onSubmit, onCancel, rated, ratedStars }) {
  const [rating, setRating] = useState(0);
  const [hover, setHover] = useState(0);
  const [comment, setComment] = useState("");

  if (rated) {
    return (
      <div className="flz-rated-banner">
        <h3>Rating successfully submitted</h3>
        <p>Thank you for your feedback!</p>
        <div className="flz-rated-stars">
          {[1, 2, 3, 4, 5].map((i) => (
            <span key={i} style={{ color: i <= ratedStars ? "#ffcc00" : "#ddd" }}>★</span>
          ))}
        </div>
      </div>
    );
  }

  return (
    <div className="flz-rating-card">
      <h2>Berikan Penilaian!</h2>
      <p className="flz-rating-sub">Berikan penilaian terhadap freelancer anda:</p>
      <div className="flz-stars">
        {[1, 2, 3, 4, 5].map((val) => (
          <span
            key={val}
            className={`flz-star${rating >= val || hover >= val ? " active" : ""}`}
            onClick={() => setRating(val)}
            onMouseEnter={() => setHover(val)}
            onMouseLeave={() => setHover(0)}
          >
            ★
          </span>
        ))}
      </div>
      <label className="flz-rating-label">Kritik & saran!</label>
      <textarea
        className="flz-rating-textarea"
        placeholder="Tuliskan pengalaman anda secara detail"
        value={comment}
        onChange={(e) => setComment(e.target.value)}
      />
      <div className="flz-rating-actions">
        <button className="flz-btn-cancel" onClick={onCancel}>Batal</button>
        <button className="flz-btn-submit" onClick={() => onSubmit(rating, comment)}>
          Kirim Ulasan! &gt;
        </button>
      </div>
    </div>
  );
}

function Modal({ show, children }) {
  return (
    <div className={`flz-modal-bg${show ? " show" : ""}`}>
      <div className="flz-modal-box">{children}</div>
    </div>
  );
}

function ProjectCard({ project, selected, onClick }) {
  return (
    <div className={`flz-proj-card${selected ? " selected" : ""}`} onClick={onClick}>
      <div className="flz-card-left">
        <h3>{project.title} <span className="flz-tag">{project.tag}</span></h3>
        <p>{project.desc}</p>
        <div className="flz-prog-row">
          <div className="flz-bar">
            <div className={`flz-fill ${project.st}`} style={{ width: `${project.progress}%` }} />
          </div>
          <span>{project.progress}% Done</span>
        </div>
      </div>
      <div className="flz-card-right">
        <div className="flz-card-date">
          <small>Deadline</small>
          {project.deadline}
        </div>
        <div className="flz-avatars">
          {project.avatars.map((a) => (
            <img key={a} src={`https://i.pravatar.cc/30?img=${a}`} alt="" />
          ))}
        </div>
        <span className={`flz-pill ${project.st}`}>{project.status}</span>
      </div>
    </div>
  );
}

// ── MAIN COMPONENT ────────────────────────────────────────────────────
export default function ProjectPage({ onChangePage, currentPage }) {
  const [activeTab, setActiveTab] = useState("ONGOING");
  
  // Load initial projects from localStorage
  const [projects, setProjects] = useState(() => {
    const saved = localStorage.getItem('client_projects');
    if (saved) {
      try {
        return JSON.parse(saved);
      } catch (e) {
        console.error('Failed to parse client_projects:', e);
      }
    }
    return DEFAULT_PROJECTS;
  });

  const [selectedId, setSelectedId] = useState("anniversary");
  const [approved, setApproved] = useState(false);
  const [rated, setRated] = useState(false);
  const [ratedStars, setRatedStars] = useState(0);
  const [modal, setModal] = useState(null);
  const [showSuccessPopup, setShowSuccessPopup] = useState(false);
  const [currentUser, setCurrentUser] = useState(null);

  // Sync to localStorage
  useEffect(() => {
    localStorage.setItem('client_projects', JSON.stringify(projects));
  }, [projects]);

  useEffect(() => {
    const link = document.createElement("link");
    link.rel = "stylesheet";
    link.href = "https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css";
    document.head.appendChild(link);

    const userStr = localStorage.getItem("user");
    if (userStr) {
      setCurrentUser(JSON.parse(userStr));
    }

    const handleStorageSync = (e) => {
      if (e.key === 'client_projects' && e.newValue) {
        try {
          setProjects(JSON.parse(e.newValue));
        } catch (err) {
          console.error(err);
        }
      }
    };
    window.addEventListener('storage', handleStorageSync);

    return () => {
      document.head.removeChild(link);
      window.removeEventListener('storage', handleStorageSync);
    };
  }, []);

  const selectedProject = projects.find((p) => p.id === selectedId);

  const getActiveStep = (p) => {
    if (!p) return 1;
    if (p.isMain && approved) return 4;
    return p.step;
  };

  const currentStep = getActiveStep(selectedProject);

  const handleConfirmApprove = () => {
    setApproved(true);
    setModal(null);
    setProjects(prev => prev.map(p => p.id === 'anniversary' ? {
      ...p,
      status: 'COMPLETED',
      st: 'cp',
      progress: 100,
      step: 4,
      cat: 'COMPLETED'
    } : p));
  };

  const handleGoToChat = () => {
    setModal(null);
    onChangePage?.("chat");
  };

  const handleRatingSubmit = (stars, _comment) => {
    setRatedStars(stars);
    setRated(true);
    setShowSuccessPopup(true);
  };

  const filtered = projects.filter((p) => p.cat === activeTab);

  return (
    <div className="flz-wrap">
      <style>{styles}</style>

      {/* HEADER */}
      <header style={{ width: '100%' }}>
        <nav style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', padding: '15px 5%', height: '70px', backgroundColor: '#000066' }}>
          <div
            style={{ color: '#ccff00', fontSize: '26px', fontWeight: '900', fontStyle: 'italic', letterSpacing: '-1px', cursor: 'pointer' }}
            onClick={() => onChangePage?.('landing')}
            title="Kembali ke Landing Page"
          >FreeLanZ</div>
          <ul style={{ display: 'flex', listStyle: 'none', gap: '25px', margin: 0, padding: 0 }}>
            <li>
              <a
                href="#explore"
                style={{ textDecoration: 'none', color: currentPage === 'explore' ? '#ccff00' : 'white', fontSize: '13px', fontWeight: 'bold' }}
                onClick={(e) => { e.preventDefault(); onChangePage?.('explore'); }}
              >EXPLORE</a>
            </li>
            <li>
              <a
                href="#chat"
                style={{ textDecoration: 'none', color: currentPage === 'chat' ? '#ccff00' : 'white', fontSize: '13px', fontWeight: 'bold' }}
                onClick={(e) => { e.preventDefault(); onChangePage?.('chat'); }}
              >CHAT</a>
            </li>
            <li>
              <a
                href="#project"
                style={{ textDecoration: 'none', color: currentPage === 'project' ? '#ccff00' : 'white', fontSize: '13px', fontWeight: 'bold' }}
                onClick={(e) => { e.preventDefault(); onChangePage?.('project'); }}
              >PROJECT</a>
            </li>
          </ul>
          <div
            style={{ display: 'flex', alignItems: 'center', gap: '12px', fontSize: '13px', fontWeight: '600', color: 'white', cursor: 'pointer' }}
            onClick={() => onChangePage?.('profile')}
          >
            <span>{currentUser ? currentUser.name.toUpperCase() : "LINATA SATORO"}</span>
            <div style={{ width: '35px', height: '35px', backgroundColor: '#e0e0e0', borderRadius: '50%', display: 'flex', alignItems: 'center', justifyContent: 'center', color: '#333', overflow: 'hidden' }}>
              {currentUser && currentUser.avatarUrl ? (
                <img
                  src={currentUser.avatarUrl.startsWith('http') ? currentUser.avatarUrl : `http://localhost:5000${currentUser.avatarUrl}`}
                  alt="avatar"
                  style={{ width: '100%', height: '100%', objectFit: 'cover' }}
                />
              ) : (
                <i className="fas fa-user"></i>
              )}
            </div>
          </div>
        </nav>
      </header>

      <div className="flz-container">

        {/* HERO */}
        <div className="flz-hero">
          <div className="flz-badge">
            <span className="flz-badge-dot" />
            {currentStep === 4 ? "PROJECT COMPLETED" : "PROJECT ON TRACK"}
          </div>
          <div className="flz-hero-row">
            <div className="flz-hero-title">
              <h1>{selectedProject?.title ?? "—"}</h1>
              <p>Project #FLZ-2024-001 • Last Update: 10m ago</p>
            </div>
            <div className="flz-collab">
              <div className="flz-collab-info">
                <span>Collaboration with</span>
                <strong>{selectedProject?.collab ?? "—"}</strong>
              </div>
              <img src={`https://i.pravatar.cc/40?img=${selectedProject?.collabImg ?? 1}`} alt="collab" />
            </div>
          </div>
        </div>

        {/* STEPPER */}
        <div className="flz-stepper-card">
          <Stepper step={currentStep} />
        </div>

        {/* KONDISI BERDASARKAN STEP */}

        {/* Step 3: Final Project card (belum di-approve) */}
        {currentStep === 3 && (
          <FinalCard
            onApprove={() => setModal("approve")}
            onDecline={() => setModal("decline")}
          />
        )}

        {/* Step 4: Approved banner + Rating card */}
        {currentStep === 4 && (
          <>
            <ApprovedBanner project={selectedProject} />
            <RatingCard
              rated={rated}
              ratedStars={ratedStars}
              onSubmit={handleRatingSubmit}
              onCancel={() => onChangePage?.("project")}
            />
          </>
        )}

        {/* WORK PROJECT */}
        <div>
          <div className="flz-section-title">WORK PROJECT</div>
          <div className="flz-tabs">
            {["ONGOING", "COMPLETED"].map((tab) => {
              const count = projects.filter((p) => p.cat === tab).length;
              return (
                <div
                  key={tab}
                  className={`flz-tab${activeTab === tab ? " active" : ""}`}
                  onClick={() => { setActiveTab(tab); setSelectedId(null); }}
                >
                  {tab} ({count})
                </div>
              );
            })}
          </div>
          <div className="flz-proj-list">
            {filtered.map((p) => (
              <ProjectCard
                key={p.id}
                project={p}
                selected={selectedId === p.id}
                onClick={() => setSelectedId(p.id)}
              />
            ))}
          </div>
          {selectedProject && selectedProject.cat === activeTab && (
            <div className="flz-detail-box">
              <div className="flz-detail-hdr">
                <h3>DETAIL: {selectedProject.title}</h3>
                <button className="flz-close-btn" onClick={() => setSelectedId(null)}>[X]</button>
              </div>
              <p style={{ fontSize: 12, color: "#555" }}>{selectedProject.desc}</p>
              <div className="flz-detail-meta">
                <div><strong>Status:</strong> {selectedProject.status}</div>
                <div><strong>Progress:</strong> {selectedProject.progress}% Done</div>
                <div><strong>Deadline:</strong> {selectedProject.deadline}</div>
              </div>
            </div>
          )}
        </div>
      </div>

      {/* MODAL — APPROVE CONFIRM */}
      <Modal show={modal === "approve"}>
        <button className="flz-modal-close" onClick={() => setModal(null)}>×</button>
        <div className="flz-success-ring">✓</div>
        <div className="flz-modal-title">Approve this project?</div>
        <div className="flz-modal-sub">
          You are approving the work submitted {selectedProject?.collab}.<br />
          This project will be marked as <strong>Completed</strong>.
        </div>
        <button className="flz-modal-btn" onClick={handleConfirmApprove}>Yes, Approve!</button>
      </Modal>

      {/* MODAL — DECLINE / REVISI */}
      <Modal show={modal === "decline"}>
        <button className="flz-modal-close" onClick={() => setModal(null)}>×</button>
        <div style={{ fontSize: 38, marginBottom: 14 }}>📝</div>
        <div className="flz-modal-title">Request Revision?</div>
        <div className="flz-modal-sub">
          Declining will send this project back for revision.<br />
          A message will be sent to {selectedProject?.collab} via Chat.
        </div>
        <button className="flz-modal-btn-sec" onClick={() => setModal(null)}>Cancel</button>
        <button className="flz-modal-btn" onClick={handleGoToChat}>Go to Chat →</button>
      </Modal>

      {/* SUCCESS POPUP — after rating submit */}
      {showSuccessPopup && (
        <div className="flz-success-popup">
          <div className="flz-popup-icon">
            <i className="fas fa-check-circle" />
          </div>
          <h2 className="flz-popup-h2">Rating successfully submitted</h2>
          <p className="flz-popup-p">Terima kasih atas ulasan Anda!</p>
          <button
            className="flz-popup-btn"
            onClick={() => {
              setShowSuccessPopup(false);
              onChangePage?.("project");
            }}
          >
            Back to mainpage!
          </button>
        </div>
      )}
    </div>
  );
}